rest:
  ssl: true
  host: ri.inpa.gov.br
  port: 443
  nameSpace: /server

# Theme Config
themes:
  - name: inpa
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/inpa/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: icon
        href: assets/inpa/images/favicons/favicon.svg
        type: image/svg+xml
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/inpa/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/inpa/images/favicons/manifest.webmanifest