rest:
  ssl: true
  host: ri-api.inpa.gov.br
  port: 443
  nameSpace: /server

defaultLanguage: pt-BR

# Theme Config
themes:
  - name: inpa_bha_col_en
    extends: inpa
    handle: 1/40044

  - name: inpa_bha_col_es
    extends: inpa
    handle: 1/40049

  - name: inpa_bha_col_pt
    extends: inpa
    handle: 1/40046

  - name: inpa_bha
    extends: inpa
    handle: 1/38510

  - name: inpa
