rest:
  ssl: true
  host: ri-api.inpa.gov.br
  port: 443
  nameSpace: /server

themes:
  - name: inpa_bha_col
    extends: inpa
    handle: 1/40046

  - name: inpa_bha
    extends: inpa
    handle: 1/38510

  - name: inpa